### ISSUE TITLE
Error in logged in Mailbox

### ISSUE THREAD

**Issue by digitalosaurus** [afterlogic/webmail-lite#100]
Hi,
I hope this repo is still supported, I tried to make webmial-lite responsive and got some errors and a white screen in the afterlogin section of the webmail; Common_HeaderViewModel template is missing. What I find strange, because its there with following code:

`<html><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252"></head><body><div class="right" data-bind="dropdown: {control: false}">
	<span class="control">
		<span class="icon"></span>
	</span>
	<span class="dropdown">
		<span class="dropdown_helper">
			<span class="dropdown_arrow"><span></span></span>
			<span class="dropdown_content">
				
				<span class="item emails" data-bind="css: {&#39;current&#39;: $parent.currentTab() === Enums.Screens.Mailbox &amp;&amp; isCurrent() },
					 click: function () { if (isCurrent()) { App.Routing.setHash(Enums.Screens.Mailbox); } else { changeAccount(); } } ">
					<span class="text" data-bind="text: email"></span>
				</span>
				

				
				<a data-bind="attr: {&#39;class&#39;: &#39;item &#39; + name, href: hash},
						css: {&#39;current&#39;: $parent.currentTab() === name, &#39;recivedAnim&#39;: koRecivedAnim}">
					<span class="text" data-bind="text: title"></span>
				</a>
				
				
				<span class="item full_version" data-bind="click: switchToFullVersion">
					<span class="text" data-i18n="HEADER/FULL_VERSION" data-bind="i18n: &#39;text&#39;"></span>
				</span>
				<span class="item logout" data-bind="click: logout">
					<span class="text" data-i18n="HEADER/LOGOUT" data-bind="i18n: &#39;text&#39;"></span>
				</span>
			</span>
		</span>
	</span>
</div></body></html>`

Hope you can help!

**Comment by afterlogic-support** [comment]
WebMail Lite v7 is discontinued. Switching over to [WebMail Lite v8](https://github.com/afterlogic/webmail-lite-8) is strongly advised. Also, if you're looking for mobile-friendly web interface, take a look at [WebMail Pro](https://afterlogic.com/webmail-client).
