### ISSUE TITLE
Can work with localhost smtp

### ISSUE THREAD

**Issue by eetsceeck1** [afterlogic/webmail-lite#101]
Hi, 
this script can work with localhost smtp server? 
and there is any option to create users?

thank you

**Comment by afterlogic-support** [comment]
> this script can work with localhost smtp server?

Yes but you need both IMAP and SMTP servers. On Windows, you can use free [hMailServer](https://www.hmailserver.com/) solution; on Linux, various options like [iRedMail](https://www.iredmail.org/) are available.

> and there is any option to create users?

No, standalone WebMail cannot do that as it's not something that can be done via IMAP or SMTP. Users need to be created with whichever tools your mailserver software offers for that.

**Comment by afterlogic-support** [comment]
Also note that version 7 is no longer supported, you may be looking for [WebMail Lite v8](https://github.com/afterlogic/webmail-lite-8) instead.

**Comment by eetsceeck1** [comment]
Thank you very much for a quick response!!!
i just installed it on my server last night and I couldn't find any option to create users that is why i was wondering, 
now its clear! looks awesome script by the way, 
thank you!
