### ISSUE TITLE
Can i use it with multiple IMAP accounts, not jus as identities / sub-account - similar to a non-web IMAP-Client OR Outlook365?

### ISSUE THREAD

**Issue by jayjupdhig** [afterlogic/webmail-lite#102]
- Can i use it with multiple IMAP accounts, not jus as identities / sub-account - similar to a non-web IMAP-Client OR Outlook365?

- If yes: What PHP version is necessary?

Thanks in advance for your feedback.

With kind regards from Switzerland,
Jan

**Comment by jayjupdhig** [comment]
What's the difference between "webmail-lite-8" and "webmail-lite" - https://github.com/afterlogic/webmail-lite-8 vs. https://github.com/afterlogic/webmail-lite ?

**Comment by jayjupdhig** [comment]
-> https://github.com/afterlogic/webmail-lite-8/issues/86

**Comment by afterlogic-support** [comment]
Answered at:
https://github.com/afterlogic/webmail-lite-8/issues/86

**Comment by kosuodhmwa** [comment]
thx! :-)
