### ISSUE TITLE
Automatically Populating "To:" Field When Opening Compose Window in Iframe Integration 

### ISSUE THREAD

**Issue by slinkys76** [afterlogic/webmail-lite#106]
Hello,

I'm currently integrating AfterLogic WebMail Lite into my application using an iframe, and I'm looking for a way to directly open the compose email window and pre-fill the "To:" field with a specific email address (like a mailto link). I understand that this might involve passing parameters through the URL or utilizing the WebMail Lite API, but I'm not sure how to approach this.

Is there a recommended method to achieve this? Specifically, I'd like to open the compose window and automatically add an email address to the "To:" field when it's opened through the iframe integration. Any guidance or examples on how to implement this feature would be greatly appreciated.

Thank you for your assistance.

**Comment by afterlogic-support** [comment]
There's no such functionality currently available. Please feel free to post a feature request at: https://afterlogic.uservoice.com/forums/932335-webmail-pro
We use that resource when developing product's roadmap, so if the feature gets a good number of votes, there's a better chance of it getting implemented. The particular section is for WebMail Pro but if such a feature gets implemented, it'll positively be there for Lite as well.
