### ISSUE TITLE
How can I do autoresponder

### ISSUE THREAD

**Issue by sblmasta** [afterlogic/webmail-lite#18]
Hello.
How Can I do own autoresponder system?
Abstract class is empty, I don't know what functions make changes.
https://github.com/afterlogic/webmail-lite/blob/master/libraries/afterlogic/common/plugins/autoresponder.php
I don't see any interface or something other.

Please help, tell me, how Can I write autoresponder plugin.

**Comment by afterlogic** [comment]
WebMail Lite already has autoresponder implemented, it relies on Sieve functionality. To use that, you need ManageSieve service running on the server, and mailserver must have Sieve support. Detailed explanation of this is found at: http://www.afterlogic.com/forum/forum_posts.asp?TID=5341

**Comment by sblmasta** [comment]
Ok, is this comptabile with virtual vacation in MySQL?
I'm using postfix + dovecot with virtual account/vacation in MySQL database.

**Comment by afterlogic** [comment]
No, Sieve rules are stored as files, not as database entries.

**Comment by sblmasta** [comment]
So, is possible to write individual implementation of autoresponder like my vacation in mysql?
Do you have some interface or abstract?

**Comment by afterlogic** [comment]
No idea, sorry. Answering that would require involving the developers.
If you are interested in ordering paid consulting services and/or custom development, you can request assistance at: http://www.afterlogic.com/development-services
