### ISSUE TITLE
Trying to delete items in trash crashes Firefox

### ISSUE THREAD

**Issue by Goddard** [afterlogic/webmail-lite#19]
I am using firefox and have about 2638 items in the trash right now.  For some reason it crashes when I click the select all checkbox item.  I think the processing is happening on the front end here?  I haven't looked at the code, but I think this is a serious problem.  Please let me know if you need more information.

**Comment by afterlogic** [comment]
In fact, when you use "select all" tool, that only covers emails which are displayed on current page of the message list. So total number of emails shouldn't matter much here. The question is, how many emails per page do you have set - and if you set to a smaller value, say 20 or 10, does the problem persist? Also, do you encounter the same problem in other folders or it's just Trash?

**Comment by Goddard** [comment]
Just the default amount.  It is a fresh install.

**Comment by afterlogic** [comment]
Okay, but does the problem occur for any other folder or it's something specific to Trash folder?

**Comment by afterlogic** [comment]
Can you please confirm whether this occurs in current 7.5 version, with Mozilla Firefox 37 used?

Thank you.

**Comment by afterlogic** [comment]
According to the other issue thread, the problem no longer occurs with that FF version.
