### ISSUE TITLE
Backspace usage in content editor crashes Firefox

### ISSUE THREAD

**Issue by rla** [afterlogic/webmail-lite#22]
Already filed under the Firefox bugtracker too: https://bugzilla.mozilla.org/show_bug.cgi?id=1147773

Could be tangentially related to #19 as WebMail might contain some specific code that is able to crash Firefox. Browser crashes should not be that common.

**Comment by afterlogic** [comment]
Thank you, we've had this reported by several users now, will investigate.

**Comment by rla** [comment]
The referenced Firefox issue is said to be fixed in the version 37.

**Comment by afterlogic** [comment]
Can you please confirm whether this still occurs with version 37 of Firefox used? Thanks.

**Comment by rla** [comment]
Does not happen with 37.0.1 on 64-bit Slackware Linux.

**Comment by afterlogic** [comment]
Understood, thanks!
