### ISSUE TITLE
Cant pull json data

### ISSUE THREAD

**Issue by kabelo38** [afterlogic/webmail-lite#25]
Hey i always get a redirect to login page

**Comment by afterlogic** [comment]
Please describe what exactly you're doing and what are the expected results. Thanks.

**Comment by kabelo38** [comment]
Hi I would like to connect to my team viewer account and pull Connection reports
My previous attempts have failed my problem is the auth process not sure if its clear

**Comment by afterlogic** [comment]
Sorry, no idea how any of that is related to our product.
