### ISSUE TITLE
How to activate Two Step Authentication on WebMail Lite PHP ?

### ISSUE THREAD

**Issue by PeopleInside** [afterlogic/webmail-lite#26]
Hi,
i can't find instruction on how activate Two step Authentication 
https://github.com/afterlogic/webmail-lite/blob/master/libraries/afterlogic/common/plugins/two-factor-auth.php

I want activate it for security as the login form didn't have captcha (i followed instruction for add captcha but not work) and also for defence to brute force attack.

So first question is:
HOW TO ACTIVATE TWO STEP AUTHENTICATION?
I hope this is possible with WebMail Lite, it's security

 And also one activated the protection will cover only web or also email client? If protect also email client i will need generate application password?

Thanks.

**Comment by afterlogic** [comment]
This functionality isn't currently available, it will be there in upcoming version 7.6.
