### ISSUE TITLE
Support for PDO/SQLite

### ISSUE THREAD

**Issue by AnnoyingTechnology** [afterlogic/webmail-lite#27]
Would it be feasible to enable a PDO/SQLite option during installation instead of PDO/MySQL, or does webmail-lite use features that are specific to the MySQL engine ? 

Thanks.

**Comment by afterlogic** [comment]
There's no easy way for us to answer that as the code was never meant to be tested for SQLite compatibility. A while ago, we've added PostgreSQL support but that took quite a lot of work.
