### ISSUE TITLE
Data transfer has failed (Error)

### ISSUE THREAD

**Issue by krosoftware** [afterlogic/webmail-lite#29]
Hello
sometimes, when I try to send email which contains image, I see error message as you can see (attached).
When I delete all images from email, then I can send it without a problem.
What can be the problem?
![after](https://cloud.githubusercontent.com/assets/8056218/10714395/b43195de-7aee-11e5-9dfc-2a5ac89afd78.PNG)
Thank you.

**Comment by afterlogic** [comment]
That seems to be a problem on web server level, checking webserver / PHP logs should help.

**Comment by krosoftware** [comment]
Hello
same email works without any error on Rundcube an Squirell email.
I asked my hosting for help but they said I need to use email client which works ...
