### ISSUE TITLE
Regarding closed issue #29

### ISSUE THREAD

**Issue by krosoftware** [afterlogic/webmail-lite#30]
Hello
same email works without any error on Rundcube an Squirell email.
I asked my hosting for help but they said I need to use email client which works ...

**Comment by afterlogic** [comment]
To find out what exactly is causing the problem, you need to examine error logs of web server and PHP. It's not really possible for us to assist you there without the relevant log records.

**Comment by krosoftware** [comment]
I contacted server support already, they said there is no error in the log file (they asked, from address, to address, subject of message). What I saw is the error on JavaScript console (you can see it on my first image - it looks like POST does not work for images which actually does not exists (please see image below:

![image](https://cloud.githubusercontent.com/assets/8056218/10785213/d041b6f2-7d62-11e5-9163-e1a4c770ebda.png)

**Comment by afterlogic** [comment]
Could be so, yes. But still, according to console output, it's webserver-level error with code 403. There has to be something in error logs on the server.

**Comment by krosoftware** [comment]
Hello
inside /public_html/mail/error_log 
is just this
    
[06-Oct-2015 06:21:37 UTC] PHP Warning:  fread(): \MailSo\Base\StreamWrappers\SubStreams::stream_read - read 41 bytes more data than requested (8233 read, 8192 max) - excess data will be lost in /home/notimportant/libraries/MailSo/Base/Utils.php on line 1737
[25-Oct-2015 06:33:04 UTC] PHP Fatal error:  Call to a member function GetData() on a non-object in /home/notimportant/libraries/ProjectCore/Actions.php on line 871 

I deleted same records.

Is there some other place where I can take a look?

**Comment by afterlogic** [comment]
These seem to be unrelated, and the error probably occured before WebMail code could be executed. So, again, this is about webserver logs - Apache and/or PHP ones.
