### ISSUE TITLE
i18n not loaded for newly activated plugin 

### ISSUE THREAD

**Issue by allanrbo** [afterlogic/webmail-lite#33]
1. Install Webmail Lite and use it (so a data/cache folder gets created)
2. Add this line to config.php:
	'plugins.two-factor-authentication' => true,

Expected: No i18n issues
Actual: Labels related to the plugin become like this: AUTHENTICATION_PLUGIN/TAB_NAME
![image](https://cloud.githubusercontent.com/assets/240223/12007288/9b6b6648-abfd-11e5-86a6-2d7f54e9b1b4.png)

**Known workaround**: delete data/cache so it gets recreated.

(ps.: thank you for a great product :-) )

**Comment by afterlogic** [comment]
Confirmed, thank you. We've updated documentation on the plugin:

http://www.afterlogic.com/wiki/Two-factor_authentication_%28WebMail%29

Regards, Igor,
AfterLogic Team
