### ISSUE TITLE
Cannot upload files 	larger than 2MB

### ISSUE THREAD

**Issue by foi** [afterlogic/webmail-lite#34]
hi!

Env:
Windows server 2012
XAMPP (apache 2.4.17, php-5.6.15)
WebMail Lite 7.6.6 
MariaDB 5.5
settings.xml
`
<EnableAttachmentSizeLimit>Off</EnableAttachmentSizeLimit>
<AttachmentSizeLimit>102400000</AttachmentSizeLimit>
<ImageUploadSizeLimit>10240000</ImageUploadSizeLimit>
`

![too_bog](https://cloud.githubusercontent.com/assets/26715/12776502/0c2436f4-ca89-11e5-92cd-e6b8a1572e93.jpg)

**Comment by afterlogic-support** [comment]
Most likely, that's caused by PHP configuration. Please see:
http://www.afterlogic.com/wiki/Error_while_attaching_files_to_new_message_(WebMail_Lite)#PHP_configuration
