### ISSUE TITLE
identitys in webmailer and postfix

### ISSUE THREAD

**Issue by mrtplink** [afterlogic/webmail-lite#38]
Hi,

see attached screenshot. If i use this settings i can send a message with the webmailer from adress service@paypal.com. If I use Outlook oder Thunderbird etc. I can Not send a message.

http://prntscr.com/ankuhc

I configure postfix for reject messages from unknown domains, but only in the webmailer with the identities i have problems, maybe you can help me on this problem. It would be cool if the webmailer checks the identities, maybe if the identities are active on the server.

**Comment by mailbee** [comment]
Hi,

Maybe you have different policies in your mail server for different IP addresses (i.e Outlook and other external clients are not allowed to send from any address while webmail is on localhost and can send from any address even if does not exist). Anyway, it's better to address this question to techsupport/community of your mails server (as why it behaves differently for different clients).
