### ISSUE TITLE
Updating to use `mysqli_*`

### ISSUE THREAD

**Issue by u01jmg3** [afterlogic/webmail-lite#39]
Is there a future intention to update [`\common\db\mysql\` & `\common\db\pdo\`](https://github.com/afterlogic/webmail-lite/tree/master/libraries/afterlogic/common/db) to use [`mysqli_*`](https://secure.php.net/manual/en/book.mysqli.php) over the deprecated `mysql_*`?

**Comment by afterlogic-support** [comment]
Indeed, we plan to update that in the future, there is no ETA yet though.

**Comment by u01jmg3** [comment]
Would you accept a PR for this change? Are we talking within 2016? I only ask because we are using your product but plan to upgrade to a newer PHP and would like to plan whether we can continue using WebMail Lite.

**Comment by mailbee** [comment]
Well, I don't think WebMail Lite will work with PHP7 even if you update to mysqli. So it must be much more complex change to make it work.

**Comment by afterlogic-support** [comment]
In fact, looks like mysql_ still works in PHP 7.

**Comment by u01jmg3** [comment]
`mysql_` is deprecated in PHP 5.6 and completely removed in PHP 7

**Comment by afterlogic-support** [comment]
Yes, that's right. Quick test shows that WebMail Lite works with PHP 7 just fine. I'm waiting for insight from the developers on this, but apparently mysql_* isn't used in current version of the product.

**Comment by afterlogic-support** [comment]
Developers confirmed WebMail uses PDO for MySQL access.
