### ISSUE TITLE
Login Option Not Working

### ISSUE THREAD

**Issue by adueck** [afterlogic/webmail-lite#44]
I have adjusted the settings.xml file as per the [documentation](http://www.afterlogic.org/docs/webmail-lite/configuring-webmail/configuring-webmail-via-settings-xml-file) to be able to login using a username and not an email.

But I am still not able to log into my IMAP/SMTP account using a user name. 

I use a account which needs a login something like this
login: `username45`
which is different than the email which something like
address: `username@domain.org`

As per the [documentation](http://www.afterlogic.org/docs/webmail-lite/configuring-webmail/configuring-webmail-via-settings-xml-file) it looks like this should be possible by changing the settings.xml file. I have added/changed the following lines.

`<OutgoingSendingMethod>Specified</OutgoingSendingMethod>`
`<LoginFormType>Login</LoginFormType>`
`<LoginAtDomainValue>domain.org</LoginAtDomainValue>`
`<UseLoginWithoutDomain>Off</UseLoginWithoutDomain>`
`<UseLoginAsEmailAddress>Off</UseLoginAsEmailAddress>`

But I am still not able to login using my `username` 

P.S. (Not sure if the `UseLoginAsEmailAddress` works as it was not in the Lite documentation)

**Comment by afterlogic-support** [comment]
Specified value for OutgoingSendingMethod setting only works as default one, it cannot be used as default domain setting. If you check Default settings under Domains in AdminPanel, you'll only find "No authentication" and "Use incoming mail's login/password of the user" options for SMTP authentication there.

**Comment by afterlogic-support** [comment]
I've discussed this with the developers team, and most likely, we'll be bringing the option back to Default settings in the next version of the product. Right now, this looks much like a bug as the options are there in settings.xml file but have no effect for the actual accounts.

**Comment by adueck** [comment]
I actually got it to work now! I just tried changing
`<UseLoginWithoutDomain>Off</UseLoginWithoutDomain>`
to
`<UseLoginWithoutDomain>On</UseLoginWithoutDomain>`
and now I'm able to use it. :smile: 

It looks like the [documentation](http://www.afterlogic.org/docs/webmail-lite/configuring-webmail/configuring-webmail-via-settings-xml-file#webmail-section) is wrong for that one option, the descriptions for `onit should be reversed.

> <UseLoginWithoutDomain>Off</UseLoginWithoutDomain>
> Determines whether email or just its username part should be used as mail server login.
> * Off - username is sent as mail server login;
> 
> * On - full email address is sent as mail server login.
> 
> The option is supported starting from v7.1.1.
