### ISSUE TITLE
Always trying to connect via port 26 when sending emails

### ISSUE THREAD

**Issue by noor8380** [afterlogic/webmail-lite#45]
Hello,

Even though I configure SMTP to use SSL on port 465, the webmail tries to send it via port 26.

Any reasons why?

Thanks

LOG
-----
[20:43:48.37][2279c448] [POST(20)][ip:94.29.220.105] /email/?/Ajax/
[20:43:48.37][2279c448] POST > [AccountID, FetcherID, IdentityID, DraftInfo, DraftUid, To, Cc, Bcc, Subject, Text, IsHtml, Importance, Sensitivity, ReadingConfirmation, InReplyTo, References, Action, ShowReport, SentFolder, Token]
[20:43:48.37][2279c448]
[20:43:48.37][2279c448] Previous Exception: Can't connect to host "tcp://mail.arksglobalconsulting.com:26"
[20:43:48.37][2279c448] exception 'CApiManagerException' with message 'Connect to mail server failed' in /home/protonla/public_html/arks/email/libraries/afterlogic/common/managers/mail/manager.php:1175
Stack trace:
#0 /home/protonla/public_html/arks/email/libraries/ProjectCore/Actions.php(1598): CApiMailManager->sendMessage(Object(CAccount), Object(MailSo\Mime\Message), NULL, 'INBOX.Sent', '', '')
#1 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#2 /home/protonla/public_html/arks/email/libraries/ProjectCore/Service.php(340): call_user_func(Array)
#3 /home/protonla/public_html/arks/email/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#4 /home/protonla/public_html/arks/email/index.php(104): include('/home/protonla/...')
#5 {main}

Next exception 'ProjectCore\Exceptions\ClientException' with message 'Can't connect to host "tcp://mail.arksglobalconsulting.com:26"' in /home/protonla/public_html/arks/email/libraries/ProjectCore/Actions.php:1619
Stack trace:
#0 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#1 /home/protonla/public_html/arks/email/libraries/ProjectCore/Service.php(340): call_user_func(Array)
#2 /home/protonla/public_html/arks/email/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#3 /home/protonla/public_html/arks/email/index.php(104): include('/home/protonla/...')
#4 {main}

**Comment by noor8380** [comment]
Seems like the database was not updated even when update tables action was done.
Had to manually change the port in the table wmai_awm_accounts to the working SMTP port.

**Comment by afterlogic-support** [comment]
If you change default settings, that will not affect accounts already set up in WebMail database. You either need to delete and recreate accounts to have them inherit new settings, or fix the values in the database directly, the way you did.
