### ISSUE TITLE
Qauth Suggestion for Webamil Lite

### ISSUE THREAD

**Issue by satdav** [afterlogic/webmail-lite#46]
Hi would you be able to add https://auth0.com/pricing to the software as this would be good and I believe easy to add

**Comment by afterlogic-support** [comment]
You can post feature requests at: https://afterlogic.uservoice.com
If a feature gets substantial amount of votes, we'll consider implementing it.
Alternately, since we're speaking of opensource software here, you can implement the feature yourself and provide a fork for original version.

**Comment by afterlogic-support** [comment]
Also, we can implement such plugin for you in terms of sponsored development. Please contact us at http://helpdesk.afterlogic.com/ if you are interested.
