### ISSUE TITLE
cPanel Install

### ISSUE THREAD

**Issue by joejordanbrown** [afterlogic/webmail-lite#51]
Seems to be a problem with Admin Panel login when using the Lite version. I've been testing this today on a number of servers. The Pro version works fine and I can access the admin at /3rdparty/afterlogic/adminpanel/index.php trying this with the Lite version I get the following error message: 

> Wrong login and/or password. Authentication failed.

In logs all i see is:

> [03:15:00.67][cea80fb9] POST > [AdmloginInput, AdmpasswordInput, enter]
> [03:15:00.67][cea80fb9]
> [03:15:00.67][cea80fb9] Location: index.php?auth_error

**Comment by afterlogic-support** [comment]
Is this a blank install or upgrade from previous version?
In case of upgrade, you need to reset password as shown at:
https://www.afterlogic.com/docs/webmail-lite/frequently-asked-questions/how-to-reset-admin-password

**Comment by afterlogic-support** [comment]
Also note that, in case of embedded cPanel install, you need to log into email account first, and only then you can log into AdminPanel.

**Comment by joejordanbrown** [comment]
It was a fresh install. Like I said it's only with the lite version, I tested this on 5 separate VPS that I setup for testing. The pro version works fine. 

Your settings.xml in the lite version has the password set in plaintext to 12345 which is obviously why the problem occured. 

I'll push a fix.

**Comment by afterlogic-support** [comment]
Oh, you're right. Thank you for pointing that out. We've corrected the problem in the repository.
(sorry for discarding the pull request)
