### ISSUE TITLE
Question: OpenGPG  

### ISSUE THREAD

**Issue by nyancat18** [afterlogic/webmail-lite#53]
thenderbird has plugins for encrypt your email content

but webmail-lite?

**Comment by afterlogic-support** [comment]
OpenPGP support is available in the Pro version only:
https://afterlogic.com/webmail-client
https://afterlogic.com/docs/webmail-pro/configuring-webmail/enabling-openpgp-support
https://afterlogic.com/docs/webmail-pro/frequently-asked-questions/using-openpgp
