### ISSUE TITLE
Not Able to Send HTML Issues

### ISSUE THREAD

**Issue by nw8311** [afterlogic/webmail-lite#54]
Hello, While composing a E-Mail I have no option to use HTML formatting. Is this feature not included or is there something wrong with my installation. Thanks

**Comment by afterlogic-support** [comment]
Hello,
Do you mean you don't have richtext controls above message editor area, such as Undo/Redo, Bold, Italic, Underline etc.? Or does it look exactly the same as Live Demo at https://lite.afterlogic.com/ ?

**Comment by nw8311** [comment]
Yes it looks like that. Is it possible to add HTML Source to an E-Mail?

**Comment by afterlogic-support** [comment]
No, the product only supports editing using richtext controls. You're most welcome to add other features you require, of course.
