### ISSUE TITLE
An error occurred while sending the message.

### ISSUE THREAD

**Issue by leocampbel** [afterlogic/webmail-lite#55]
Hello, everyone, thank you for the open source project!

I installed and configured everything correctly, but when sending an email the error occurs: An error occurred while sending the message.

I do not know what it is, my server uses ssl.

Attached the log:

I hope you can help me, because I really want to use the afterlogic.

Thank you!
[log-2017-07-21.txt](https://github.com/afterlogic/webmail-lite/files/1166278/log-2017-07-21.txt)

**Comment by afterlogic-support** [comment]
I suspect your server uses STARTTLS rather than SSL on SMTP level. Try unchecking SSL option and see if it works that way. If you change that in Default settings, you'll need to remove and recreate WebMail account for those changes to apply.

If it still doesn't work, please post the updated logs so we could take a look. Thanks.

**Comment by leocampbel** [comment]
Hi, I've done what you asked me to do.
When you click Send, you receive the following message:
Failed to transfer data, possibly due to server error. Please contact the administrator.

But the email reaches the recipient.
Follow the log.
Thanks for the help!
[event-2017-07-22.txt](https://github.com/afterlogic/webmail-lite/files/1167052/event-2017-07-22.txt)
[log-2017-07-22.txt](https://github.com/afterlogic/webmail-lite/files/1167053/log-2017-07-22.txt)

**Comment by afterlogic-support** [comment]
These logs don't contain any errors, see if there's anything relevant in PHP/webserver logs. The error message you quoted usually shows up if there was a webserver level error.

**Comment by tigranos** [comment]
Hi, please help to fix an issue.
after sending a message. i got an error
An error occurred during sending the message.

And no additional info
