### ISSUE TITLE
An error occurred during sending the message. (Can't connect to host "ssl://smtp.gmail.com:456")

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#57]
this error happned when i tried to send email.I have install webmail-lite locally.Also this error happened 
An error occurred during sending the message. (Can't connect to host "ssl://smtp-mail.outlook.com:587")
OS : ubuntu

**Comment by afterlogic-support** [comment]
Typically, 587 is port for STARRTLS and not SSL. Uncheck SSL box and try again.

**Comment by abdelrahmanahmed** [comment]
same error ,
PS : i am using this plugin 
https://afterlogic.com/docs/plugins-repository/override-default-domain-settings

**Comment by afterlogic-support** [comment]
If it's still shows ssl:// in the error message, SSL access was not disabled for the account. You may need to delete and recreate the account so that default settings apply to it.

**Comment by abdelrahmanahmed** [comment]
i read this documentation
https://afterlogic.com/docs/webmail-pro/configuring-webmail/managing-domains-and-users
i cant delete any user or even finding them. should i empty the database?

**Comment by afterlogic-support** [comment]
You're referring to WebMail Pro documentation while this is actually about WebMail Lite which doesn't offer management of domains and users. Under default domain settings in AdminPanel, make sure you have "Allow users to remove their primary accounts" option checked, then you should be able to find "Remove account" option under Settings > Common.
