### ISSUE TITLE
Bug in admin style.css

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#60]
I don't know is it even possible to add js into css files?
i saw this line in admin stylesheet (adminpanel/static/styles/style.css) 
```
body {
	height:expression((document.getElementsByTagName('body')[0].offsetHeight < document.getElementsByTagName('html')[0].offsetHeight) ? '100%' : '');

}
```

**Comment by afterlogic-support** [comment]
I'm not sure what bug you're referring to.

**Comment by abdelrahmanahmed** [comment]
this line in your stylesheet 
`height:expression((document.getElementsByTagName('body')[0].offsetHeight < document.getElementsByTagName('html')[0].offsetHeight) ? '100%' : '');`

its useless and not working , if yous see developer tool you will find that its not rendered.

**Comment by abdelrahmanahmed** [comment]
![image](https://user-images.githubusercontent.com/8146379/28871900-fb8ce690-7786-11e7-9818-91ef1cf09407.png)
here is a screenshot

**Comment by afterlogic-support** [comment]
It's intended for older IE browsers. It does nothing in new browsers. If you don't care about old IE, you can delete this. But this is certainly not a bug and was added intentionally.
