### ISSUE TITLE
Is it possible to get specific from or to or even searching in subject

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#61]
How can i search and get list of **to** or **from**  or searching in **email subject**?

**Comment by afterlogic-support** [comment]
Programmatically or in UI?

**Comment by abdelrahmanahmed** [comment]
Programmatically

**Comment by afterlogic-support** [comment]
Unfortunately, no ready examples available. You can use https://afterlogic.com/docs/webmail-pro/integration-and-development/getting-new-or-last-messages for start and extend it with specifying extra parameters of getMessageList function (in webmail/libraries/afterlogic/common/managers/mail/manager.php) which let you configure search. That's all we can suggest..

**Comment by abdelrahmanahmed** [comment]
I have noticed this in the UI 
![image](https://user-images.githubusercontent.com/8146379/28945119-6d206d80-78a5-11e7-9166-d2d2afc46949.png)
can you tell me what are the methods used in this search?

**Comment by afterlogic-support** [comment]
If you put a breakpoint in getMessageList function, you'll see which parameters are passed after you type them in search box in UI. With a bit of experimenting you should get the idea what to pass there.
