### ISSUE TITLE
bidirectional text when sending and email

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#62]
Is it possible to change the direction of text by clicking ctrl+shift (LRT to RTL or RTL to LTR) , when sending an email? because sometimes i want to write Arabic text , or English text.
![image](https://user-images.githubusercontent.com/8146379/29034833-dd079712-7b99-11e7-9c23-cb03016e35ca.png)

**Comment by afterlogic-support** [comment]
Please see: https://afterlogic.com/docs/webmail-lite/frequently-asked-questions/how-to-enable-rtl-controls-on-compose-but-keep-non-rtl-interface-language

Does it help?

**Comment by abdelrahmanahmed** [comment]
unfortunately no, i need the text when i want RTL to started here like in this image
![1](https://user-images.githubusercontent.com/8146379/29038481-17d5241e-7ba8-11e7-81df-3fedaf114f2e.jpg)

and when i want to write LTR i want the text to start here 

![2](https://user-images.githubusercontent.com/8146379/29038496-2a5d4bc0-7ba8-11e7-97f1-b1f8e38610e6.jpg)

and switching between them (ctrl + shift )

**Comment by afterlogic-support** [comment]
Switching that way isn't currently supported. Positioning of the cursor looks incorrect indeed though, developers will take a look.

**Comment by abdelrahmanahmed** [comment]
Can i help you ? i just don't know where should i write my custom js in a way that your did it in the project

**Comment by abdelrahmanahmed** [comment]
Is there align center in the text editor ?

**Comment by afterlogic-support** [comment]
Not sure what you're asking. We definitely would consider accepting pull request, should you submit one. The consulting on source code modification, however,  is beyond free support though. Thank you for understanding.

**Comment by abdelrahmanahmed** [comment]
Does this feature even exist (align text  left-center-right) ?
![image](https://user-images.githubusercontent.com/8146379/29068084-8e645608-7c35-11e7-8ba1-4b66e3850316.png)

**Comment by afterlogic-support** [comment]
Have answered that at:
https://github.com/afterlogic/webmail-lite/issues/63
