### ISSUE TITLE
Enable Align when send email

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#63]
How to enable align text when sending email ? like in this image
![image](https://user-images.githubusercontent.com/8146379/29081497-0b5b7074-7c63-11e7-8baa-7e46fbed48fb.png)

**Comment by afterlogic-support** [comment]
WebMail Lite doesn't currently have that. If you believe this feature would be a popular demand, you can post a vote at http://afterlogic.uservoice.com/ - and if the feature gets substantial number of votes we'll consider implementing it in the future versions.

**Comment by abdelrahmanahmed** [comment]
ok thats wired , because i found that u were already implemented it .
```
function () { oCrea.alignLeft(); }
function () { oCrea.center(); }
function () { oCrea.alignRight(); }
function () { oCrea.justify(); }
```

**Comment by afterlogic-support** [comment]
As far as I know it's still in the codebase but the feature was removed in one of the previous versions, there's no easy way to bring that back, not without extensive modification of the skins and templates.

**Comment by abdelrahmanahmed** [comment]
Well for those who want to bring it back  you can just edit in **templates/views/Common/HtmlEditorViewModel.html**
and add 
```
<a href="javascript:void(0);" class="item aleft" data-bind="click: function () { oCrea.alignLeft(); }, customTooltip: 'HTMLEDITOR/ALIGN_LEFT'">
				<span class="icon"></span>
			</a>
```
and in your css  add 
```
.html_editor .toolbar .content .item.aleft .icon {
  background-position: -320px -320px;
}
```

note : you can find the other aligning methods in **static/js/libs.js**


I have no idea why you removed it  but i appreciate your work @afterlogic-support , you did a great project here.

**Comment by abdelrahmanahmed** [comment]
@afterlogic-support  should i add pull request for this or you don't want this feature to return back?

**Comment by afterlogic-support** [comment]
I've checked this with our UX dept and they confirm the feature was deliberately removed a while ago. Also, the button images are outdated and would need to be redesigned. So in this specific case, I'm afraid we would turn a request down. Thank you for understanding.
