### ISSUE TITLE
How to solve Allow less secure app problem to send emails

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#64]
I have a gmail account and it works only if i enabled allow less secured app in my gmail settings, is there a way to send emails without allowing this option?

**Comment by afterlogic-support** [comment]
There currently isn't one. Gmail believes that any authentication method based on username/password is insecure - and it would apply to pretty much any other IMAP client out there, including Outlook and Thunderbird - as long as they use email and password for authentication.

In future versions, we're going to implement OAuth authentication for email access; that's what we're currently using in Files for working with Google Drive. This isn't happening within v7 though, we're talking of WebMail Lite 8 here: https://github.com/afterlogic/webmail-lite-8/
