### ISSUE TITLE
Creating new identity does't work probably 

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#65]
I have Added a new identity with new email and new name, for example 
 primary email : **wahdan@domain.com** with name **wahdan**
 new identity : **test@domain.com** with name **test**

when i am trying to send email from test@domain , it appears in the receiver 
from **name** : test ,  **email** wahdan@domain.com

Do i miss something? i assumed that the email should be test@domain.com not wahdan@domain
but the result was different.

**Comment by afterlogic-support** [comment]
That largely depends on mail server you're sending from. While many servers allow for supplying a "fake" sender's email, there are servers that won't allow that (and WebMail can't do anything about it).
Keep in mind: whatever information you supply in Identity, you're still using the original account info on SMTP level.
https://afterlogic.com/docs/webmail-lite/configuring-webmail/how-to-use-or-disable-identities

**Comment by abdelrahmanahmed** [comment]
Well the problem is in the sent folder , it appears name test and the email wahdan@domain.com, so the problem isn't with the server. also test@domain.com isn't a fake email , this is just an example , i have to gamil accounts that on one of them rely on the other. Should i check something else?

**Comment by afterlogic-support** [comment]
In Sent folder, message is uploaded by WebMail. It's not guaranteed that the recipient will get it in exactly the same way. And no, there's nothing else to check there. If the sender's server forces actual From address, you cannot override that behavior using an identity.
