### ISSUE TITLE
Logging in programmatically

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#67]
I have read this [documentation](https://afterlogic.com/docs/webmail-lite/integration-and-development/logging-in-programmatically)  and applied it in my code and it worked.But the problem is sometimes it redirect to the login page ,even if i refresh the page it redirects to login page and i am 100% sure the username and password is correct , how is that possible ?

**Comment by afterlogic-support** [comment]
Without extra debug information (like, does the behavior differ with the same set of data supplied) it's hard to suggest anything. I'd recommend to observe the properties of p7auth cookie which is used for authentication purposes - do they always look the same, or sometimes they differ, e.g. point to different domain or path? Most likely, that would be where the reason is.

**Comment by abdelrahmanahmed** [comment]
well i have noticed that p7auth doen't exist at all, i have checked my config and i have found that my app url is set to localhost , and when i run my project i have logged automatically , but when i type my ip instead of localhost (or when i set my app url to my ip and type localhost) the login page appear  ,and i think this is the  problem . but i don't know why it happens ?

**Comment by afterlogic-support** [comment]
Is the integration code located within the same web directory as the webmail installation? And are those within the same domain, from URL point of view?

**Comment by abdelrahmanahmed** [comment]
Ok I have found the answer,when i set my config (app url) to 192.168.1.20 the cookies are set to this domain ,when i type localhost in browser url instead of my ip (without changing my config) the login page appeared , because there are no cookies in localhost , the cookies are set in 192.168.1.20 not localhost (and vise versa)
