### ISSUE TITLE
Error, session support in PHP must be enabled....

### ISSUE THREAD

**Issue by Nurlan199206** [afterlogic/webmail-lite#68]
![image](https://user-images.githubusercontent.com/22808731/29882274-5b298042-8dce-11e7-9409-355c15b96aa2.png)

how to fix this issue? I am using Centos 6.8 and PHP version 5.6

PHP session is enabled.

![image](https://user-images.githubusercontent.com/22808731/29882355-8ee5db1a-8dce-11e7-84ec-1dc09caf227f.png)

/var/lib/php/session folder is writable

**Comment by afterlogic-support** [comment]
To test if that's a PHP configuration issue, please download the following script:

[http://www.afterlogic.com/files/session_test.zip](http://www.afterlogic.com/files/session_test.zip)

Unpack and place it into WebMail directory, then run it from web browser, to see if it displays OK or ERROR.

**Comment by Nurlan199206** [comment]
![sess](https://user-images.githubusercontent.com/22808731/29918047-beec8eac-8e65-11e7-92ef-3bb9ac793ab8.PNG)

not working

**Comment by afterlogic-support** [comment]
Then it's indeed session-related issue with PHP configuration, not related to our product. Checking with PHP community support may help.
