### ISSUE TITLE
would love a dark theme

### ISSUE THREAD

**Issue by unalignedcoder** [afterlogic/webmail-lite#71]
Hello I'm just starting to use this, is part of my getting-rid-of-gmail process. It seems great. Was wondering if it could be possible to have a dark theme or the ability to set up the colors of the theme or at least the background image.

**Comment by afterlogic-support** [comment]
You can customize an existing skin or create your own one using the following guidelines:
https://afterlogic.com/docs/webmail-pro/integration-and-development/creating-new-skin
