### ISSUE TITLE
[Q] MailSo library documetnation

### ISSUE THREAD

**Issue by Med-All** [afterlogic/webmail-lite#72]
Is there any documentation on MailSo library?

I'm looking for some examples how to extract attachments from the original message, create new message which will include those extracted attachments and a body of an original message and then send that via MailSo again (as SMTP) to Apache James mail server for further automatization.

As the webmail is using that library I want to avoid using 3rd party library like PHPmailer on top of MailSo.

**Comment by afterlogic-support** [comment]
Currently, there's no documentation available for this library.
