### ISSUE TITLE
An error occurred while sending the message

### ISSUE THREAD

**Issue by siatto** [afterlogic/webmail-lite#73]
> An error occurred while sending the message

Incoming mail *
(imap.domain.com) : 993 Use SSL

Outgoing mail *
(smtp.domain.com) : 587 Don't Use SSL

SMTP Authentication
Use incoming mail's login/password of the user

**Would you help me?**

**Comment by afterlogic-support** [comment]
To find out what's causing the problem, you need to log into AdminPanel, enable logging there, make sure Verbosity level is set to Debug, replicate the problem and check for SMTP-related errors recorded in the logs. If you share the logs here we may be able to offer some further help.

**Comment by pradnyeshs** [comment]
same issue i am facing . i can receive the emails but not able to send the mail. i configured through thunderbird for cross check , on which it works properly, 
my inbound port is 143 & out server is 25. 
any suggestion for this issue???????????????

**Comment by pradnyeshs** [comment]
it is showing this log.
[18:05:01.36][e02eed55] IMAP[NOTE]: Start connection to "tcp://localhost:143"
[18:05:02.37][e02eed55] IMAP[DATA]: < * OK IMAPrev1\r\n
[18:05:02.37][e02eed55] IMAP[DATA]: > TAG1 CAPABILITY\r\n
[18:05:02.37][e02eed55] IMAP[DATA]: < * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL NAMESPACE RIGHTS=texk\r\n
[18:05:02.37][e02eed55] IMAP[DATA]: < TAG1 OK CAPABILITY completed\r\n
[18:05:02.37][e02eed55] IMAP[SECURE]: > TAG2 LOGIN "ps@psmail.ml" "********"\r\n
[18:05:02.37][e02eed55] IMAP[DATA]: < TAG2 OK LOGIN completed\r\n
[18:05:02.38][e02eed55] SMTP[NOTE]: Start connection to "tcp://localhost:25"
[18:05:03.38][e02eed55] SMTP[DATA]: < 220 psmail.ml ESMTP\r\n
[18:05:03.38][e02eed55] SMTP[DATA]: > EHLO www.psmail.ml\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 250-psmail.ml\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 250-SIZE 20480000\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 250-AUTH LOGIN\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 250 HELP\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: > AUTH LOGIN\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 334 VXNlcm5hbWU6\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: > QWRtaW5pc3RyYXRvcg==\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 334 UGFzc3dvcmQ6\r\n
[18:05:03.39][e02eed55] SMTP[SECURE]: > ********\r\n
[18:05:03.39][e02eed55] SMTP[DATA]: < 535 Authentication failed. Restarting authentication process.\r\n


, i checked all password also.

**Comment by afterlogic-support** [comment]
According to the logs, it's a different login used for SMTP ("Administrator", not "ps@psmail.ml"). I'd assume that's where the issue is, typically login/password would be the same for IMAP and SMTP.

**Comment by pradnyeshs** [comment]
so what can be the solutions, as i used same user/pass for both smtp and imap.
what should be the setting in domain setting?? i chose incoming user user/pass , or it should be no authentication ?? trying hard to get this problem solved,

**Comment by afterlogic-support** [comment]
It needs to be the same login and password for IMAP and SMTP. But according to the logs, it's not the case. Somewhere in the configuration you have Administrator specified for SMTP credentials and I'd suggest to check there.

**Comment by pradnyeshs** [comment]
i checked all passwords but still it is showing authentication error , i am using hmail server which working fine for mobile devices and thinderbird, is there any configuration file in which i can change smtp login credentials??

**Comment by afterlogic-support** [comment]
No, it's in the database only. You may wish to delete and recreate the database, and configure the accounts from scratch.

**Comment by pradnyeshs** [comment]
thanks for your great support. if fixed my problem. loved to use this. ♥

**Comment by BhagyashreeKoyande** [comment]
An error is occured while sending message. Could you please help?
I am attaching the log file,please check
log-2020-08-01 (1).txt

**Comment by BhagyashreeKoyande** [comment]
Error while sending mail , please help me.
I am attaching log file
(_removed by @afterlogic-support for privacy reasons_)

**Comment by afterlogic-support** [comment]
Make sure you have SMTP authentication enabled, most mail servers out there will not allow for sending mail out (to other domains, at least) without SMTP auth.
Also, seems you're using an old v7 of the product, which is discontinued. Using current version 8 is recommended.

**Comment by BhagyashreeKoyande** [comment]
Thankyou for your response, SMTP authentication is enabled but then to mail is not send, Also about the version 8 , it does not contain install folder like version 7 so I am not understanding how to configure it in my localhost xamp

**Comment by afterlogic-support** [comment]
> SMTP authentication is enabled but then to mail is not send

According to the logs, SMTP authentication was not enabled, mail server responded with "530-5.7.0 Authentication Required." message.

> about the version 8 , it does not contain install folder like version 7

Indeed it doesn't. You simply log into admin interface with default credentials **superadmin**/**12345** and configure the installation by setting up database details, mail server configuration etc.:
https://afterlogic.com/docs/webmail-lite-8/configuring-webmail
And just like v7, it offers Compatibility Test, it's a good idea to run one to make sure the environment meets the system requirements of the product:
https://afterlogic.com/docs/webmail-lite-8/installation/compatibility-test

Should you need assistance with WebMail Lite, feel free to request help at the [community forum](https://s.afterlogic.com/forum/forum_topics.asp?FID=28).

**Comment by BhagyashreeKoyande** [comment]
Thankyou so much for your help. I installed and configured version 8 and its working good.
Thankyou once again!
