### ISSUE TITLE
Login config

### ISSUE THREAD

**Issue by SandeepanSengupta** [afterlogic/webmail-lite#74]
I'm having trouble configuring the login page.

I need @gmail / @roundcube styled login i.e if the **login** is **name@example.com**, user can enter either **username** (i.e _name_) or **entire login** (i.e _name@example.com_). If user enters username only, @ and example.com will be automatically appended. But if user enters entire login, it will not.

Now, according to the Afterlogic Webmail-Lite documentation I did the following

**LoginFormType** -> _Login_
**LoginAtDomainValue** -> _sandeepan.info_
**UseLoginWithoutDomain** -> _On_

It didn't helped.

Then I noticed that there are two files in **\data\settings** directory
1. settings.xml
2. settings.xml.bak

And it appeared that _settings.xml.bak_ is **continuously overwriting** _settings.xml_ file

I tried modifying the **settings.xml.bak** file and it crashed my domain (email.sandeepan.info)

Please provide a way to resolve this issue.

Note: My question may be trivial and I apologize for my limited knowledge in this topic

**Comment by afterlogic-support** [comment]
> user can enter either username (i.e name) or entire login (i.e name@example.com).

WebMail Lite doesn't support this kind of behavior, it can only be one of those types of credentials but not both.

> And it appeared that settings.xml.bak is continuously overwriting settings.xml file

This occurs if there was an error made in data/settings/settings.xml file. When modifying the file, make sure to maintain valid XML syntax.

**Comment by SandeepanSengupta** [comment]
> WebMail Lite doesn't support this kind of behavior, it can only be one of those types of credentials but not both.
OK
>This occurs if there was an error made in data/settings/settings.xml file. When modifying the file, make sure to maintain valid XML syntax.
These are the settings I was using
```
<LoginFormType>Login</LoginFormType>
<LoginSignMeType>DefaultOn</LoginSignMeType>
<LoginAtDomainValue>sandeepan.info<LoginAtDomainValue/>
<UseLoginWithoutDomain>On</UseLoginWithoutDomain>

```

**Comment by afterlogic-support** [comment]
> <LoginAtDomainValue>sandeepan.info<LoginAtDomainValue/>

That's incorrect XML syntax. The correct one would be:

<LoginAtDomainValue>sandeepan.info</LoginAtDomainValue>

**Comment by SandeepanSengupta** [comment]
Thank you @afterlogic-support
