### ISSUE TITLE
How to get All inbox

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#75]
I was trying to get mails in a specific folder using this method [getMessageList](https://afterlogic.com/aurora-docs/api/class-CApiMailManager.html) and it worked perfectly, is there a method that gets all mails related to the $`oAccount` ?

**Comment by afterlogic-support** [comment]
WebMail can only access one folder at a time; that's actually a limitation of IMAP protocol.
