### ISSUE TITLE
Usage of webmail database

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#76]
I have installed webmail locally with it's database , i have noticed these two tables `awm_messages` , `awm_messages_body` . What are they used for ? . Does the webmail stores emails in the database ? Is there any documentation for the installed database ?

**Comment by afterlogic-support** [comment]
Those are legacy tables. In older versions, the product supported storing messages in the database - that was especially handy for POP3 accounts. As of v7, that is no longer supported and the tables aren't used.

**Comment by abdelrahmanahmed** [comment]
But i am using webmail 7 already  , why webmail installed database locally ?

**Comment by afterlogic-support** [comment]
Yes, those database tables are still created, but they're not actually used.

Note that version 8 of WebMail Lite is available already: https://afterlogic.org/webmail-lite
