### ISSUE TITLE
Searching in multiple folders at once

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#77]
According to your documentation i can get all mail from a specific folder using [getMessage()](https://afterlogic.com/aurora-docs/api/class-CApiMailManager.html) method  , can i pass  `$sFolderFullNameRaw` with multiple folders name?

**Comment by afterlogic-support** [comment]
That's not supported out-of-box, but since we're speaking of open-source software, you're welcome to make any modifications so the product and its API meets your requirements.
