### ISSUE TITLE
getMessageList() in class CApiMailManager.php and returning the next mail 

### ISSUE THREAD

**Issue by abdelrahmanahmed** [afterlogic/webmail-lite#79]
I am trying to get emails using this method [getMessageList](https://afterlogic.com/aurora-docs/api/class-CApiMailManager.html) but i am confused about `$sInboxUidnext` attribute ,  is this to get messages after this Uid ? also is there a way to get messages after specific Uid?

Thanks,

**Comment by afterlogic-support** [comment]
Hello,

This issue tracker is in place, as the name suggests, for reporting issues with the product. And we don't usually mind answering various questions regarding the product - however, if you need assistance with product integration and customization that requires in-depth knowledge of how the product and its API works, it can be arranged in terms of Professional Services contract. Please [contact us](mailto:support@afterlogic.com) if interested.
