### ISSUE TITLE
Text not properly show up

### ISSUE THREAD

**Issue by APCS-SD** [afterlogic/webmail-lite#81]
Today, I just updated webmail to latest v8, but the text on the left column cannot show the text propery. Both in the mail pages or admin setting pages. I tried to change language to English, but I can not work as well. I will attached the photo of what I am look after login to the webmail. And how to solve it. 
![default](https://user-images.githubusercontent.com/21992845/36975543-60feccc8-20b5-11e8-99db-1169ec34387f.png)

**Comment by afterlogic-support** [comment]
> I just updated webmail to latest v8

Did you actually update from v7, or earlier v8? Or this was a blank install?

> I tried to change language to English, but I can not work as well.

Can you provide a screenshot of how it looks if you switch web interface to English?

Please also try deleting content of data/cache/ directory and see if that helps.

**Comment by APCS-SD** [comment]
1. It is a blank install on a cPanel hosting platform. I have another webmail v7 running on the same host server but in a different domain, database, and directory.
2.
![default](https://user-images.githubusercontent.com/21992845/36977438-18bd7b88-20bc-11e8-995c-5a3810297061.png)

**Comment by afterlogic-support** [comment]
We were unable to reproduce the issue locally, did a test install on cPanel and it all displays correctly there as well, both in English and Chinese:

![lite8cpanel](https://user-images.githubusercontent.com/16918936/37021238-f3dd8f78-212f-11e8-9ad2-a50d1cf3e837.png)

If you check Live Demo at https://lite.afterlogic.com/ - does it show correctly for you there?

Also, is it possible to provide us with a test account on your WebMail install? Can't promise anything but we would take a look. Please use [our HelpDesk](s.afterlogic.com/helpdesk/) to provide account details.

**Comment by APCS-SD** [comment]
I install another copy on different server (It is VPS not cPanel), it could work on that. But this one just don't work. So it should not be the problem of my browser. 
BTW the HelpDesk link not work, it is a 404 page.

**Comment by afterlogic-support** [comment]
HelpDesk is found at https://s.afterlogic.com/helpdesk/

As for the first installation, I don't think it's browser-related; probably something with the server, maybe some of the files were not uploaded there.

**Comment by afterlogic-support** [comment]
Developers confirm it's a server-level issue related to loading images. Most likely, the server is configured to access images from some sort of CDN storage but the images are part of the installation and should be retrieved from their actual location.
