### ISSUE TITLE
Cant access to admin page

### ISSUE THREAD

**Issue by ysilvela** [afterlogic/webmail-lite#83]
I cant acces to the admin page in http://domain.com:2095/3rdparty/afterlogic/adminpanel/index.php in my domain.

I try with the superuser but no login. I use cpanel

I not have settings.xml. In /usr/local/cpanel/base/3rdparty/afterlogic/data/settings I only have a config.json

Another question. Why I only access to one domain account? The other account request a login page.

Thanks.

**Comment by afterlogic-support** [comment]
Apparently, you have v8 installed, and it doesn't have AdminPanel indeed. See this documentation page:
https://afterlogic.com/docs/webmail-lite-8/installation/install-on-cpanel
