### ISSUE TITLE
Wrong sort order in folders

### ISSUE THREAD

**Issue by Lorodion** [afterlogic/webmail-lite#91]
Hello,

The messages in all folders are sorted by the time that they were moved into the folder. Not the time that the message was received/sent, which I thought should be the default sort order.

For example, if I take a message A from page 10 in folder B and move it to folder C and then back to B - it is now displayed at the top of page 1 in folder B. I expect it to be on page 10 like before.

Is it possible to change this?

**Comment by afterlogic-support** [comment]
By default, WebMail lists messages in their natural order as they're returned by IMAP server - and that order is amended by moving mails between the folders. Still it's possible to force sorting mails by date.

Try setting **UseSortImapForDateMode** to **On** in `data/settings/modules/Mail.config.json` configuration file. 

Does it help?

**Comment by Lorodion** [comment]
Perfect, that is what I was looking for.
