### ISSUE TITLE
ManageSieve STARTTLS is disabled

### ISSUE THREAD

**Issue by Jamie0** [afterlogic/webmail-lite#93]
When connecting to ManageSieve, it is not currently possible to enable `STARTTLS` without modifying `libraries/afterlogic/common/managers/sieve/manager.php` directly.

I don't understand why the default value for `$iSecurityType` is `ConnectionSecurityType::NONE` instead of `ConnectionSecurityType::AUTO_DETECT`, or at least why this is not configurable? 

If you're running webmail on a separate host or network, it doesn't make sense to transmit plaintext user passwords over the network when communicating with ManageSieve, especially when everything else is encrypted.

**Comment by afterlogic-support** [comment]
Actually, we've just made a change that makes the behavior configurable. We appreciate sending a pull request but in this case, it cannot be accepted I'm afraid.

**Comment by afterlogic-support** [comment]
The change we're referring to will become available in the next version 8.2.4.
