### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by team-sevenm** [afterlogic/webmail-lite#96]
Hey! Some of our clients have reported that while logging in with their own credentials, they see (or are logged-in as) usernames of other account holders (on our server) without any mails in the interface. 

Like in the screenshot attached, A user logged in from a different account shown in the picture but was shown an altogether different user's account without any mails in it.
Please resolve.

![Screenshot_1](https://user-images.githubusercontent.com/56807483/67169826-8feb8b80-f3cb-11e9-9071-bb401df265be.jpg)

**Comment by afterlogic-support** [comment]
Are you using a control panel of some sort and WebMail was installed integrated with it, or you installed it from ZIP package? Also, is there a chance that the users are using the same web browser on the same computer?

**Comment by team-sevenm** [comment]
Hi!

We installed from the ZIP link downloaded on your website. Our servers run
cPanel.

No, we are talking of different computers, geographically located in
different locations.

**Comment by afterlogic-support** [comment]
Can you confirm which version you're on? 
https://afterlogic.com/docs/webmail-lite-8/troubleshooting/detecting-version-used
From the screenshot, it looks like older v7 which is discontinued. Make sure you're on the latest v8:
https://afterlogic.org/webmail-lite
