### ISSUE TITLE
Problem displaying the interface in Russian

### ISSUE THREAD

**Issue by qaWskYer** [afterlogic/webmail-lite#97]
There was a problem displaying the interface in Russian. Text blocks do not load strings from l18n: MAILBOX/TOOL_NEW_MESSAGE
MAIN/FOLDER_INBOX
HEADER/CONTACTS etc
Localization works fine with other languages.
There was an error in the file /l18n/Russian.ini - in the last field in the ACCOUNT_PASSWORD_RESET section in BODY there was an extra character ". Fixed, but it doesn’t work anyway.
Help solve the problem.

**Comment by afterlogic-support** [comment]
To apply changes made in language files, be sure to purge `data/cache` directory content.

And thank you for reporting the issue.
