### ISSUE TITLE
issue while logging in webmail lite 7

### ISSUE THREAD

**Issue by shouvikkrsarkar** [afterlogic/webmail-lite#98]
[09:02:18.08][3b53b3bd] ProjectCore\Exceptions\ClientException: ClientException in /home/vol1_6/epizy.com/epiz_25589670/email.easymailb.ga/htdocs/libraries/ProjectCore/Actions.php:3069
Stack trace:
#0 [internal function]: ProjectCore\Actions->AjaxAccountRegister()
#1 /home/vol1_6/epizy.com/epiz_25589670/email.easymailb.ga/htdocs/libraries/ProjectCore/Service.php(341): call_user_func(Array)
#2 /home/vol1_6/epizy.com/epiz_25589670/email.easymailb.ga/htdocs/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#3 /home/vol1_6/epizy.com/epiz_25589670/email.easymailb.ga/htdocs/index.php(104): include('/home/vol1_6/ep...')
#4 {main}

Please help. I am not able to register into webmail lite and this is the error stack trace. I am using webmail lite 7.

**Comment by afterlogic-support** [comment]
Looks like you're trying to use an account signup feature but it won't work with a standalone Webmail Lite, it's meant for use in a mailserver bundle. What you need to do is [configure default domain settings](https://afterlogic.com/docs/webmail-lite/configuring-webmail/configuring-default-domain-settings), then you'll be able to login with any account you have on your mailserver.
 
**NB:** WebMail Lite 7 is no longer supported, switching to current version is strongly advised:
https://afterlogic.org/webmail-lite
