### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by DeMessias** [afterlogic/webmail-lite#99]
Hi @afterlogic-support team, I've installed Webmail Lite via Softaculous but unfortunately I'm not able to login with an email address. Could you please advise? Where can I put a datalog and screenshots? Greetings.

**Comment by afterlogic-support** [comment]
Hello,
If you provide us with test account credentials, admin login/password and the installation URL, we will take a look.
Please send those [via HelpDesk](https://s.afterlogic.com/helpdesk). WebMail Lite is a community edition and doesn't come with guaranteed free support from Afterlogic, still we may be able to assist.

**Comment by DeMessias** [comment]
Hi team,

Thanks for your quick reply. I have solved the issue already. Thanks for offering your initial assistance. Have a great day. Ciao
